---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: controller
  become: true
  roles:
    - Horizon
    - Cinder
    - Neutron
